### ISSUE TITLE
Conexión API Albergues

### ISSUE THREAD

**Issue by silmood** [erikcaffrey/AyudaMexico#14]
Añadir petición para albergues. Se está utilizando la info de una hoja de calculo por lo que la petición se lleva acabo con google apps script. Este es el link del script que funciona como endpoint:

https://script.google.com/macros/s/AKfycbzOsDlIbCFEsgTYpMG_-HI7zHnDNRDu1eT3AEla69DsYDWKsFo/exec

**Comment by erikjhordan-rey** [comment]
Done!
