### ISSUE TITLE
Botones "MAPA" e "INFO" no funcionan al hacer scroll en Centros de Acopio

### ISSUE THREAD

**Issue by QiiqeAzuara** [erikcaffrey/AyudaMexico#21]
Al momento de hacer scroll en la lista de centros de acopio los botones "MAPA" e "INFO" dejan de ser funcionales.

**Comment by silmood** [comment]
Revisé la app en la versión 1.4 y no sucede. Hay que tomar en cuenta que hay ocasiones que no existe link de más información o el link del mapa.

**Comment by QiiqeAzuara** [comment]
@silmood ya revise lo que regresa el server contra el funcionamiento de la app, y efectivamente estoy probando la versión 1.4, haz lo siguiente: Abre centros de acopio , y scrollea hasta el último centro de acopio y de ahi regrésate al primero y veras que el issue aparece. Me avisas como te fue.

**Comment by silmood** [comment]
Cierto, el problema estará en el ViewHolder del adapter de Centros de acopio. Le desactiva la opción `clickable` al encontrar un Centro de Acopio que no tenga mapa o info, pero ya recordé que no lo restaura.

**Comment by QiiqeAzuara** [comment]
@silmood ya tengo el fix, por eso me asigne, :), además se debe de utilizar un LinearLayoutManager en la lista y no un GridLayoutManager

**Comment by silmood** [comment]
Gracias :)
