### ISSUE TITLE
Modificar Sección de Donaciones 

### ISSUE THREAD

**Issue by erikjhordan-rey** [erikcaffrey/AyudaMexico#23]
- Agregar 2 tabs 2 (1 el listado actual y el 2 un webview) 
- Listado actual hacer el cardview como en la sección de "Avisos importantes"
- Agregar un webview para incluir esta URL   [Donativos Conekta](https://donativos.conekta.com/) de donaciones para cruz roja y Topos!

**Comment by DevPicon** [comment]
@erikcaffrey ya me lo asigné

**Comment by DevPicon** [comment]
@erikcaffrey PR #24

**Comment by erikjhordan-rey** [comment]
Merged!
