### ISSUE TITLE
La aplicación se detiene al dar tap en botón Mapa de 'Albergues'

### ISSUE THREAD

**Issue by jmalonsos** [erikcaffrey/AyudaMexico#25]
En la sección de Albergues al dar tap sobre los botones **Mapa** la aplicación se detiene, la url del mapa se encuentra en la propiedad `zone` y no en `map`.
<img width="621" alt="albergues" src="https://user-images.githubusercontent.com/889649/30761723-e062d636-9fa4-11e7-9a65-6066e2bb755a.png">

**Comment by silmood** [comment]
@jmalonsos Sabes si todos los items traen el link en `ZONA` ?

**Comment by jmalonsos** [comment]
@silmood En algunos casos vienen con cadena vacía, también se puede validar eso de una vez.

**Comment by silmood** [comment]
Lo que me estoy dando cuenta es que en `RECIBEN` está la dirección y la `ZONA` está en el campo `DIRECCION`. Creo que mejor hay que validarlo con el script

**Comment by erikjhordan-rey** [comment]
@jmalonsos solo valida el null y listo

**Comment by silmood** [comment]
@erikcaffrey creo que es un tema del script

**Comment by jmalonsos** [comment]
Si actualizaron recién el script, ya se ve bien la respuesta, la url ya se identifica correctamente en `MAPA`
<img width="769" alt="captura de pantalla 2017-09-22 a la s 15 05 04" src="https://user-images.githubusercontent.com/889649/30762386-74a602d0-9fa7-11e7-86f8-048897e810d3.png">

**Comment by erikjhordan-rey** [comment]
@silmood  @jmalonsos  dejen reviso el script =)

**Comment by jmalonsos** [comment]
@erikcaffrey Aún así hay que validar contra `null` o `cadena vacía` al hacer el intent para abrir el mapa. Puedo mandar el PR de ese fix.

**Comment by erikjhordan-rey** [comment]
@jmalonsos el problema es que movieron el orden de las hojas del spreadsheet. estoy revisando con el equipo que esta encargado del documento.

**Comment by erikjhordan-rey** [comment]
@jmalonsos  ya esta resuelto el tema del script! no hay que hacer nada ante eso es transparente pero si seria bueno validar para evitar posibles Null

**Comment by jmalonsos** [comment]
@erikcaffrey Listo, tengo un fix para validar si la propiedad `Mapa es null` Puedo mandar el PR, pero no tengo accesos al repositorio.

**Comment by erikjhordan-rey** [comment]
@jmalonsos  puedes mandar tu PR ya te mande invite
