### ISSUE TITLE
Retroalimentacion del equipo de Verificado19s

### ISSUE THREAD

**Issue by patanric** [erikcaffrey/AyudaMexico#30]
El usuario necesita una opción para retroalimentar sobre la exactitud de la infomración en la app que proviene del [spreadsheet](https://docs.google.com/spreadsheets/d/1mqiEdi6kba5eVVpAubUBcPjOPPUkoD_xGdbVm55Cktc/edit?ts=59c3cac8#gid=0) mantenido por https://www.coder.mx/

Tal vez un botón que abre un email con datos de la info incorrecta.

El equipo de Verificado19s mantiene la info de:

- Ayuda requirida

- Albergues

- Centro de Acopio

- Hospitales

- Avisos importantes

Siguiente paso: contactar al equipo de Verificado19s para saber como podemos trabajar juntos.

**Comment by patanric** [comment]
@erikcaffrey como me puedo asignar este issue?

**Comment by erikjhordan-rey** [comment]
El spreadsheet  `Ayuda Sismo CDMX` no tiene nada que ver con verificados19s, tampoco quiero que mi app se ligue a Verificados en la mañana acorde con ellos, solo poner su mapa así que creo que esto no será posible o no en esta app. Quiero mantenerla únicamente para ayudar a `Ayuda Sismo CDMX`, no la voy a ligar a verificados 19s

**Comment by patanric** [comment]
Entonces no había entendido. Creía que la info proviene de este [spreadsheet](https://docs.google.com/spreadsheets/d/1mqiEdi6kba5eVVpAubUBcPjOPPUkoD_xGdbVm55Cktc/edit?ts=59c3cac8#gid=537494149) y que lo mantiene verificados19s.

**Comment by patanric** [comment]
@erikcaffrey entonces como funciona exactamente? Desde dónde viene la info y a quien tendríamos que retroalimentar? Pues yo creo que es fundamental y crítico que la información en la app sea correcta. Al no ser así es muy probable que la app nunca se vuelve popular. Por eso pienso que este issue no esta listo para cerrar. Me gustaría que lo volvieras a abrir para que yo pueda trabajar en esto.

Es muy obvio que los usuarios que están en el lugar que indica la app, son los que tienen la información más precisa de los chavos que están sentados en su oficina tratando de actualizar los datos.

Como vez, Erik?

**Comment by erikjhordan-rey** [comment]
El primer punto es que https://www.coder.mx/ y verificados son mis amigos pero es un proyecto distinto y el mío quiero mantenerlo tal cual funciona ahora. No me parece bueno mezclarlo mi app sirve para la gente ellos me pidieron construir esto, toda fue construida bajo necesidad y así quiero que continue por ahora.

**Comment by Diego-Franco** [comment]
En caso de querer verificar la información (si es tanta la necesidad, ya que como se mencionó antes, la info es verificada)

Se podría tener un botón en el mismo ítem para que mandarán como una aprobación de qué es correcta o no, solo eso, no es necesario email a mí parecer

**Comment by patanric** [comment]
Bueno, lo del email fue solo una idea. pues lo que buscaba aquí era una discusión. que bueno que intervengas @Diego-Franco ! Otra idea es que por ejemplo se registra el número de personas que notificaron una falsa información y después de un cierto número se avisan los amigos que mantienen los datos.

Hay que tener en cuenta que una vez verificada (y no tengo duda que nuestros amigos lo hacen bien) se necesita también tener actualizada la info. Como podemos asegurarnos que sea asi?

Yo soy una de las personas que deinstala una app que tiene information no actualizada. Por eso creo que otros también lo hacen.

**Comment by erikjhordan-rey** [comment]
Estoy de acuerdo en verificar si claro pero no ha depender de otro esfuerzo, por que eso implica mucha coordinación de ambas partes y ambos trabajamos en cosas distintas.

Poner un simple botón de "si" o "no" me parece más que suficiente tal cual comenta @Diego-Franco.
