### ISSUE TITLE
Poner link a Google Maps en la actividad Bancos de Sangrie

### ISSUE THREAD

**Issue by patanric** [erikcaffrey/AyudaMexico#32]
El usuario necesita dar click al nombre de un hospital para que Google Maps le indique el camino.

**Comment by erikjhordan-rey** [comment]
El cardview tiene el listener no es necesario y si el usuario presiona el botón también se habré el mapa. Lo siento pero cerrare tu issue.


![image](https://user-images.githubusercontent.com/5893477/30767972-715d9f50-9fc7-11e7-9a37-ac7751e1d341.png)

**Comment by salvadormaurilio** [comment]
@erikcaffrey  creo que @patanric se refiere a esta pantalla 
![image](https://user-images.githubusercontent.com/4513422/30768007-d7dda40a-9fc7-11e7-93c8-50b777c15e3b.png)

**Comment by patanric** [comment]
asi es @salvadormaurilio

**Comment by erikjhordan-rey** [comment]
y si hay una sección de hospitales para que poner doble listener?, esa vista es un textview y la sacamos e la pagina de http://sismomexico.org/ hay que rehacer la vista y haré un release pronto, no para este release si es que alguien lo toma, @patanric tu lo haces te lo asignas?

**Comment by salvadormaurilio** [comment]
Por que tendrías que buscar primero el hospital en que puede donar sangre y luego ir a la sección de hospitales para volver a buscar el hospital y abrir el mapa, no?

**Comment by erikjhordan-rey** [comment]
@salvadormaurilio  te lo asignas?

**Comment by salvadormaurilio** [comment]
Hecho @erikcaffrey

**Comment by patanric** [comment]
ay, muchas gracias @salvadormaurilio , no vi el mensaje de @erikcaffrey . Estaba en el otro channel de slack para encontrar una persona que se dedica a difundir de forma profesional ;-)

**Comment by erikjhordan-rey** [comment]
@salvadormaurilio  lo vas a liberar en este release o el de mañana?
