### ISSUE TITLE
Integración con Centros Acopio by RescateMX

### ISSUE THREAD

**Issue by DevPicon** [erikcaffrey/AyudaMexico#51]
Se requiere integrar la aplicación con la información recolectada por RescateMX

https://cdmx.opendatasoft.com/explore/dataset/mapeocolaborativobitlyrescatemx-centrosdeacopio-colaborativo/information/

**Comment by erikjhordan-rey** [comment]
Agregar Como un tab más en "centros de acopio"

**Comment by David-Hackro** [comment]
I will take this!

**Comment by erikjhordan-rey** [comment]
#54
