### ISSUE TITLE
Integración con API de Albergues CDMX

### ISSUE THREAD

**Issue by DevPicon** [erikcaffrey/AyudaMexico#52]
Se requiere integrar la aplicación con la información disponible en :

https://cdmx.opendatasoft.com/explore/dataset/centros-de-acopio-cdmx/information/

**Comment by erikjhordan-rey** [comment]
Hay que crear tabs, en esta sección para poder agregarlo en la sección albergues.

**Comment by erikjhordan-rey** [comment]
Voy a cerrar este issue no agrega valor a la aplicación son repetidos ya tenemos los centros en la api de Ayuda Sismo Mx. (Centros de acopio CDMX son los mismos si integran morelos o puebla sería mejor
)
